### ISSUE TITLE
How do you modify the GeoNode template?

### ISSUE THREAD

**Issue by d3netxer** [csgis/geonode_ansible#3]
The scripts installed GeoNode correctly. After installation, I went to the edit the site_index.html file in the ~/my_geonode/my_geonode/templates folder but the change does not reflect on the site. Any clue on what I should do?

**Comment by t-book** [comment]
@d3netxer thanks for reporting! 

This commit should fix it: https://github.com/csgis/geonode_ansible/commit/0e0574999eaec86266fa1334ad6803986077dacf
Please add both two lines to: `~/my_geonode/my_geonode/local_settings.py`

After that the easiest to test is remove comments in:
```
$ vim ~/my_geonode/my_geonode/templates/site_base.html
```
that it looks like:
````
{% extends "base.html" %}
{% block extra_head %}
      <link href="{{ STATIC_URL }}css/site_base.css" rel="stylesheet"/>
{% endblock %}
{% block extra_tab %}
Add Tab for Third Party Apps
<li>
 <a href="{{ PROJECT_ROOT }}app">App</a>
</li>
{% endblock %}
````
and restart apache
````
$ sudo service apache2 restart
````

You should now see an extra menu item.

Cheers,

Toni

**Comment by d3netxer** [comment]
@t-book I re-installed the GeoNode using the latest code. Then I uncommented the block in the site_base.html file and I saw the app menu appear. This was great. However, then I tried to modify the site_index.html file, but no changes happened. I do not know why this is, the hero block is supposed to override the default template.

**Comment by t-book** [comment]
I´ll have a look and come back on this ;)

**Comment by d3netxer** [comment]
Thanks for the tip @t-book. I did some more digging on this. The customizations appear if I change the file name of 'site_index.html' to 'index.html'. This is because I believe that in the Django template system, the index.html file needs to extend from all other files, and if any other template files extend from it without being named 'index.html' then the changes will not be reflected. It would be great to get your thoughts on this.
